### ISSUE TITLE
v0.005-alpha: [BUG] Game list ID search

### ISSUE THREAD

**Issue by arcade-legend** [Skurdt/3DArcade#17]
Hi

As seen in a youtube video, entering "id: wboy" for example, should list all games that contain "wboy" in the game ID.
However in v0.005-alpha the ID search doesn't work at all here (in content mode). No matter what I enter after "id;", nothing is found.

PS: the v0.004-alpha bug about the content mode edit of a cabinet seems to be fixed in my latest test!

**Comment by Skurdt** [comment]
it's :id

**Comment by arcade-legend** [comment]
LOL! 
OK, very sorry!

Maybe to prevent confusion (at least for me), replace ":id" by "id:"?
It makes more sense for natural language :)

**Comment by Skurdt** [comment]
it's like a console command though. I wanted to use / but it's on the same key and requires pressing shift... so : is 1 less key

**Comment by arcade-legend** [comment]
Ok, I close this :)
