### ISSUE TITLE
v0.004-alpha: generate game list

### ISSUE THREAD

**Issue by arcade-legend** [Skurdt/3DArcade#9]
Hi

I found 2 weird problems when trying to generate a mame 0.221 compatible game list. 

- For some reason no list appears on the screen when I select my mame.exe. Maybe it's doing parsing in the background and it's not finished? I think it should display a wait mouse cursor or something. The list appears after some time however but I selected the mame.exe again because no waiting feedback is given to the user (the parsing takes a while) and I thought it was not doing anything.

- I generated a mame 0.232 game list which should have 43470 games of which are 5240 devices and 73 bios. So you end up having (parents and clones) 38157 machines that can be played (devices and bios can't run).
I opened the database and there are only 22764 games inside. I see you also included clones because of the CloneOf.
So is this a bug in your parser because more then 10000 games are missing?

See screenshot

![afbeelding](https://user-images.githubusercontent.com/85412588/121043991-6efcc780-c7b5-11eb-93b1-48cd8d6d5815.png)

Thx in advance!

**Comment by arcade-legend** [comment]
In addition I would like to request a feature to use libretro rdb database files (can be found in \database\rdb or retroarch) for generating a game list. Maybe this is not really possible because each game needs an ID and I don't know if it's present in the rdb file.
I found an interesting tool however to look at the rdb database files: https://github.com/schellingb/RDBEd

**Comment by Skurdt** [comment]
There's no wait icon yet, I'll add something like a cancel button and block all other input while it's generating the xml and parsing.
Trying to execute the process again without the previous one being completed or canceled will most certainly fail.

Right now the parser is setup to only add entries that have the "runnable" value not set to "no", are not marked as bios, mechanical or device and have their driver status set to "good" of "imperfect".

Note that at these 40k+ results, the unity UI gets extremely slow.
Also I'll probably add more settings to ignore certain drivers or things that can be recognized as not runnable other than the runnable tag, these a pretty much useless when trying to add games in an arcade (things like pinball table or fruit machine roms).

RDB files are neat, they contain data from pretty much the same sources I use and have genre, year and manufacturer data. There's a good chance I'll add support for these next.

**Comment by arcade-legend** [comment]
Is it possible to make the user decide what to include when generating a game list from mame? For example I would like some fruit machines too included because you can make whole different kind of arcades too then :)
 So you can make checkboxes to enable/disable adding specific things.

Cool! Just check the source code of the tool :p

**Comment by arcade-legend** [comment]
I was also wondering if you could make the game list have a dedicated screen to remove games by applying filters. This is to make the list you want by removing not wanted games.

Idea:

- You could first add columns year and manufacturer and let the user sort them by click the column.

- I would also love a search option for filtering on game name and/or game ID. For example; return all games with substring "racer" in the game name. 

- Then finally (after applying a search) it could be cool to allow selecting many games at the same time by holding down shift, selecting the first game and then selecting the last game from the list. Pressing DELETE key on keyboard deletes this selection from the game list.

**Comment by Skurdt** [comment]
Ignoring fruit machines and/or pinball roms when generating a mame master list has nothing to do with the ability to have fruit machines or pinballs in an arcade.
Mame will never output anything using these roms, to play either you have to use a fruit machine emulator or a pinball emulator/software. There's no point in having them in the mame masterlist, it's just useless stuff that the UI has to display.

Speaking of UI, all those features you mention are extremely hard to deal with for big lists such as mame. At 40k+ entries, the framerate dips below 20 on my 5800x and an rtx 2080 when displaying onlly the text field for description and id.
Since database editing is not something you would do everyday (once most of them are setup I mean), then using the external db tool to edit them is a way better option at this time, it can do everything you listed and much more (things I could never add to the in-game UI).

**Comment by arcade-legend** [comment]
OK, it's better to use external tools. Closed.
